<a href="https://colab.research.google.com/github/tastiz/hello-world/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

a = np.array([[2,7,10],[67,90,110]])
#print(a)

c = np.arange(20)
#print(c)

d = np.arange(3,93,3)
#print(d)

e = np.zeros(10)
#print(e)

f = np.ones((6,7))
#print(f)

g = np.arange(20)
#print(g)

g = g.reshape(4,5)
#print(g)

h = np.arange(35).reshape(5,7)
#print(h)

# print the number of axes in this array
print('There are {} axes in this array.'.format(h.ndim))

# print the shape of the array
print('This is a {} array'.format(h.shape))

# print the size of the array
print('This array contains {} elements'.format(h.size))

# print the data type of the elements
print('This array contains values of type {}'.format(h.dtype))


There are 2 axes in this array.
This is a (5, 7) array
This array contains 35 elements
This array contains values of type int64


In [28]:
cw_coursework = np.random.randint(1,35,20)
exam_coursework = np.random.randint(5,48,20)

total = cw_coursework + exam_coursework
print(cw_coursework)
print(exam_coursework)
print(total)

print('The highest mark in the couse was {}'. format(np.max(total)))
print('The lowest mark in the course was {}'.format(np.min(total)))
print('The mean mark in the course was {}'.format(np.mean(total)))
print('The standard deviation of the marks in the course was {}'.format(np.std(total)))

[ 4 14 31 16 26 22  8 10 26  1 10 20 34 31 31 11 10 30 12 29]
[11 25 11 17 12 28 22 19 41 17  8 40 46  6 47 18 36 11 20 25]
[15 39 42 33 38 50 30 29 67 18 18 60 80 37 78 29 46 41 32 54]
The highest mark in the couse was 80
The lowest mark in the course was 15
The mean mark in the course was 41.8
The standard deviation of the marks in the course was 18.03773821741518
